### ISSUE TITLE
put useful info in the readme

### ISSUE THREAD

**Issue by Haroenv** [alloy/vscode-relay#2]
I'd make a pull request, but I'm not so sure what you want in it.

**Comment by orta** [comment]
I have this locally, give me a sec

**Comment by orta** [comment]
#3

**Comment by alloy** [comment]
@Haroenv Thanks for the offer, I’ve merged @orta’s start so that it can be installed at least. If you run into specific setup steps that need to be performed to get this up and running then please do PR that. For now I haven’t moved to the step of publishing this yet.

**Comment by Haroenv** [comment]
Super
